# Universal Windows Platform
# Build a Universal Windows Platform project using Visual Studio.
# Add steps that test and distribute an app, save build artifacts, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Pool'

schedules:
- cron: '0 0 29 * *'
  displayName: Daily midnight build
  branches:
    include:
    - develop

steps:

- task: JsonPatch@4
  inputs:
    SyntaxType: 'slick'
    JsonWorkingDir: '$(Build.SourcesDirectory)'
    JsonTargetFilters: 'appdata.json'
    JsonPatchContent: '= /User/Password => "$(Password)"'
    FailIfNoPatchApplied: true
    TreatErrors: 'ERROR'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  displayName: 'Restoring nuget package for solution'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'Building solution with Debug configuration'
  inputs:
    command: 'build'
    arguments: '--configuration Debug'

- task: CmdLine@2
  inputs:
    script: |
      echo Build has been started

- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'